---
- name: install mysql packages
  yum: pkg={{ item }} state=installed
  when: ansible_os_family == "RedHat"
  sudo: true
  with_items:
    - mysql
    - mysql-server
    - MySQL-python

- name: make sure mysql starts
  command: chkconfig mysqld on
  sudo: true

## set up mysql variables
#- name: create MySQL configuration file
#  action: template src=redhat_mysql.my.cnf.j2 dest=/etc/my.cnf
#  sudo: true
#  notify: 
#  - restart mysqld

- name: get iptables rules
  shell: iptables -L
  register: iptablesrules
  failed_when: "iptablesrules.rc != 0"
  changed_when: False
  always_run: yes
  sudo: true

- name: add mysql to iptables
  command: iptables -A INPUT -p tcp --dport {{ mysql_port }} -j  ACCEPT  -m comment --comment "mysql"
  sudo: true
  when: iptablesrules.stdout.find("mysql") == -1
  notify:
   - save iptables

- name: force restart mysql
  service: name=mysqld state=restarted
  sudo: true

# MySQL database setup, this does the equivalent of mysql_secure_installation.
#- name: set the root password.
#  mysql_user: name=root password={{ mysql_root_password }} host=localhost

#- name: config for easy access as root user
#  template: src=mysql_root.my.cnf.j2 dest=/root/.my.cnf
#  sudo: true

#- name: config for easy access as root user
#  template: src=mysql_root.my.cnf.j2 dest=/home/{{ user }}/.my.cnf

#- name: delete anonymous MySQL server user for {{ server_hostname }}
#  mysql_user: name="" host="{{ server_hostname }}" state="absent" login_user=root login_password={{ mysql_root_password }}

#- name: delete anonymous MySQL server user for localhost
#  mysql_user: name="" state="absent" host="{{ server_hostname }}" login_user="root" login_password="{{ mysql_root_password }}"

#- name: secure the MySQL root user for IPV6 localhost (::1)
#  mysql_user: name="root" password="{{ mysql_root_password }}" host="{{ server_hostname }}" login_user=root login_password={{ mysql_root_password }}

#- name: secure the MySQL root user for IPV4 localhost (127.0.0.1)
#  mysql_user: name="root" password="{{ mysql_root_password }}" host="{{ server_hostname }}" login_user=root login_password={{ mysql_root_password }}

#- name: secure the MySQL root user for localhost domain (localhost)
#  mysql_user: name="root" password="{{ mysql_root_password }}" host="{{ server_hostname }}" login_user=root login_password={{ mysql_root_password }}

#- name: secure the MySQL root user for {{ server_hostname }} domain
#  mysql_user: name="root" password="{{ mysql_root_password }}" host="{{ server_hostname }}" login_user=root login_password={{ mysql_root_password }}

#- name: remove the MySQL test database
#  mysql_db: db=test state=absent login_user=root login_password={{ mysql_root_password }}
#  
# set up default database
#- name: create application database
#  mysql_db: name={{ dbname }} state=present login_password={{ mysql_root_password }} login_user=root

#- name: create application database user
#  mysql_user: name={{ dbuser }} password={{ dbpass }} priv=*.*:ALL host='%' state=present login_password={{ mysql_root_password }} login_user=root

# Optional database import

#- name: import database (default source file)
#  mysql_db: name={{ dbname }} state=import target=/var/www/site/vlad_aux/db_io/vlad_up.sql.gz login_password={{ mysql_root_password }} login_user=root
#  when: db_import_up is defined and db_import_up == "y"
#  ignore_errors: yes
#  tags: mysql_import

#- name: import database (specified source file)
#  mysql_db: name={{ dbname }} state=import target=/var/www/site/vlad_aux/db_io/{{ db_import_up }} login_password={{ mysql_root_password }} login_user=root
#  when: db_import_up is defined and db_import_up != "y" and db_import_up != "n"
#  ignore_errors: yes
#  tags: mysql_import
