---
- name: apache_ssl | enable ssl module
  command: a2enmod ssl creates=/etc/apache2/mods-enabled/ssl.conf
  sudo: true
  notify:
    - restart apache2

- name: apache_ssl | add vhost for ssl version of the site
  template: src=debian_apache_ssl_vhost.j2 dest=/etc/apache2/sites-available/{{ webserver_hostname }}_ssl.conf
  sudo: true
  notify:
    - restart apache2

- name: apache_ssl | enable the new site
  command: a2ensite {{ webserver_hostname }}_ssl.conf creates=/etc/apache2/sites-enabled/{{ webserver_hostname }}_ssl.conf
  sudo: true
  notify:
    - restart apache2

- name: get iptables rules
  shell: /sbin/iptables -L
  register: iptablesrules
  sudo: true
  always_run: true

- name: add apache iptable rule
  command: /sbin/iptables -I INPUT 1 -p tcp --dport 443 -j ACCEPT -m comment --comment "ssl"
  sudo: true
  when: iptablesrules.stdout.find("ssl") == -1
  notify:
   - save iptables