---
- name: apt-get | apt-get update and ensure core packages are installed
  apt: pkg={{ item }} state=installed update_cache=yes cache_valid_time=3600
  tags: aptget
  sudo: true
  with_items:
    - ssh-import-id
    - unzip
    - curl
    - atop
    - vim
    - git
    - make