---
# Load variable file based on the OS type, or a default if not found.
- include_vars: "{{ item }}"
  with_items:
   - "{{ ansible_os_family }}.yml"
   - "all.yml"

- name: get local IPv4 address
  local_action: setup filter=ansible_default_ipv4
  register: local_ipv4_address

- name: ensure vlad_aux/db_io directories exist
  file:
    path: /var/www/site/vlad_aux/{{ item }}
    state: directory
    mode: 0777
  with_items:
    - db_io
    - db_io/halt_destroy
  become: true

- include: mysql.yml

- include: mysql_import.yml
  tags: mysql_import