---
# Install and configure samba server (requires ports 137, 138, 139, 445 open).
- name: Ensure Samba-related packages are installed.
  apt: pkg={{ item }} state=installed
  with_items:
  - samba

- name: Copy VLAD shared folders into smb-vlad.conf
  template: dest=/etc/samba/smb-vlad.conf src=smb-vlad.conf
  sudo: true
    
- name: Include VLAD shared folders in smb.conf
  lineinfile: dest=/etc/samba/smb.conf line="include=/etc/samba/smb-vlad.conf"
  sudo: true
  notify: restart smbd
