---
- name: install java and tomcat packages
  yum: pkg={{ item }} state=installed
  sudo: true
  with_items:
   - icedtea-web
   - tomcat6
   - tomcat6-webapps
   - tomcat6-admin-webapps

- name: change port of tomcat server
  copy: src=tomcat/server.xml dest=/etc/tomcat6/server.xml
  sudo: true

- name: ensure correct run level of tomcat
  service: name=tomcat6 enabled=yes
  sudo: true
  notify:
   - restart tomcat6

- name: force (re)start of tomcat6
  service: name=tomcat6 state=restarted
  sudo: true

- name: copy the tomcat6 users file
  copy: src=tomcat/tomcat-users.xml dest=/etc/tomcat6/tomcat-users.xml owner=tomcat group=tomcat mode=0644
  sudo: true
  notify:
   - restart tomcat6

- name: get iptables rules
  shell: iptables -L
  register: iptablesrules
  always_run: yes
  sudo: true
  changed_when: false

- name: add tomcat iptable rule
  command: /sbin/iptables -I INPUT 1 -p tcp --dport 8081 -j ACCEPT -m comment --comment "tomcat"
  sudo: true
  when: iptablesrules.stdout.find("tomcat") == -1
  notify:
   - save iptables

- name: download apache commons logging
  command: wget http://mirrors.ukfast.co.uk/sites/ftp.apache.org/commons/logging/binaries/commons-logging-1.2-bin.tar.gz chdir=/home/{{ user }} creates=/home/{{ user }}/commons-logging-1.2-bin.tar.gz

- name: extract apache commons logging
  command: tar -zxf commons-logging-1.2-bin.tar.gz chdir=/home/{{ user }} creates=/home/{{ user }}/commons-logging-1.2
  sudo: true

- name: list commons-logging files (in order to copy)
  command: ls -1 /home/{{ user }}/commons-logging-1.2/
  register: commonsfiles

- name: copy apache commons logging
  command: cp -r /home/{{ user }}/commons-logging-1.2/{{ item }} /usr/share/tomcat6/lib creates=/usr/share/tomcat6/lib/{{ item }}
  sudo: true
  with_items: commonsfiles.stdout_lines

- name: download SLF4J
  command: wget http://www.slf4j.org/dist/slf4j-1.7.7.tar.gz chdir=/home/{{ user }} creates=/home/{{ user }}/slf4j-1.7.7.tar.gz

- name: extract SLF4J
  command: tar -zxf slf4j-1.7.7.tar.gz chdir=/home/{{ user }} creates=/home/{{ user }}/slf4j-1.7.7

- name: list slf4j files (in order to copy)
  command: ls -1 /home/{{ user }}/slf4j-1.7.7/
  register: slf4jfiles

- name: copy SLF4J
  command: cp -r /home/{{ user }}/slf4j-1.7.7/{{ item }} /usr/share/tomcat6/lib creates=/usr/share/tomcat6/lib/{{ item }}
  sudo: true
  with_items: slf4jfiles.stdout_lines
  when: "'android' not in item and 'slf4j-log4j12' not in item and 'log4j-over-slf4j' not in item and 'slf4j-jcl' not in item"

- name: download Solr
  command: wget http://www.mirrorservice.org/sites/ftp.apache.org/lucene/solr/4.7.2/solr-4.7.2.tgz chdir=/home/{{ user }} creates=/home/{{ user }}/solr-4.7.2.tgz

- name: extract Solr
  command: tar -zxf /home/{{ user }}/solr-4.7.2.tgz chdir=/home/{{ user }} creates=/home/{{ user }}/solr-4.7.2

- name: copy Solr war file
  command: cp /home/{{ user }}/solr-4.7.2/dist/solr-4.7.2.war /var/lib/tomcat6/webapps/solr.war creates=/var/lib/tomcat6/webapps/solr.war
  sudo: true

- name: list solr files (in order to copy)
  command: ls -1 /home/{{ user }}/solr-4.7.2/example/solr/
  register: solrfiles

- name: copy Solr instance
  command: cp -ar /home/{{ user }}/solr-4.7.2/example/solr/{{ item }} /home/solr creates=/home/solr/{{ item }}
  sudo: true
  with_items: solrfiles.stdout_lines

- name: rename the collection1 directory to {{ default_collection_name }}
  command: mv /home/solr/collection1 /home/solr/{{ default_collection_name }} creates=/home/solr/{{ default_collection_name }}
  sudo: true

- name: remove the collection1 collection if it is still there
  file: path=/home/solr/collection1 state=absent
  sudo: true

- name: change the name of the collection
  lineinfile: dest=/home/solr/{{ default_collection_name }}/core.properties regexp="^name=" insertafter="^name=" line="name={{ default_collection_name }}"
  sudo: true

- name: create a solr lib directory
  file: path=/home/solr/lib state=directory
  sudo: true

- name: list all jar files that are part of solr (in order to copy)
  shell: ls -1 /home/{{ user }}/solr-4.7.2/dist/ | grep .jar
  register: solrjarfiles
  changed_when: false

- name: copy solr lib files
  command: cp /home/{{ user }}/solr-4.7.2/dist/{{ item }} /home/solr/lib/{{ item }} creates=/home/solr/lib/{{ item }}
  with_items: solrjarfiles.stdout_lines
  sudo: true

- name: force restart of tomcat6
  service: name=tomcat6 state=restarted
  sudo: true

- name: add WEB-INF directory
  command: mkdir -p /var/lib/tomcat6/webapps/solr/WEB-INF/
  sudo: true

- name: copy the web.xml tomcat solr integration file
  copy: src=tomcat/redhat_web.xml dest=/var/lib/tomcat6/webapps/solr/WEB-INF/web.xml
  sudo: true

- name: copy the log4j properties file
  copy: src=tomcat/log4j.properties dest=/usr/share/tomcat6/lib/log4j.properties
  sudo: true

- name: make the {{ default_collection_name }} data directory
  command: mkdir /home/solr/{{ default_collection_name }}/data creates=/home/solr/{{ default_collection_name }}/data
  sudo: true

- name: get Drupal solr integration via search_api_solr
  git:
    repo: http://git.drupal.org/project/{{ drupal_solr_package }}.git
    dest: dest=/home/{{ user }}/drupal_solr
    version: 7.x-1.6
    depth: 1
  when: drupal_solr_package == "search_api_solr"

- name: get Drupal solr integration via apachesolr
  git:
    repo: http://git.drupal.org/project/{{ drupal_solr_package }}.git
    dest: /home/{{ user }}/drupal_solr
    version: 7.x-1.7
    depth: 1
  when: drupal_solr_package == "apachesolr"

- name: copy Drupal Solr config into Solr
  shell: cp -r /home/{{ user }}/drupal_solr/solr-conf/4.x/. /home/solr/{{ default_collection_name }}/conf/
  when: drupal_solr_package == "search_api_solr"
  sudo: true
  notify:
   - restart tomcat6

- name: copy Drupal Solr config into Solr
  shell: cp -r /home/{{ user }}/drupal_solr/solr-conf/solr-4.x/. /home/solr/{{ default_collection_name }}/conf/
  when: drupal_solr_package == "apachesolr"
  sudo: true
  notify:
   - restart tomcat6

- name: make the lib/contrib directory for the extension to live in
  command: mkdir -p /home/solr/lib/contrib creates=/home/solr/lib/contrib
  sudo: true

- name: copy the needed class directories over
  command: cp -r /home/{{ user }}/solr-4.7.2/contrib/{{ item }} /home/solr/lib/contrib/{{ item }} creates=/home/solr/lib/contrib/{{ item }}
  sudo: true
  with_items:
    - analysis-extras
    - clustering
    - dataimporthandler
    - extraction
    - langid
    - uima
    - velocity

- name: ensure tomcat/Solr directory has correct owner
  file: path=/home/solr owner=tomcat group=tomcat recurse=yes
  sudo: true