---
- name: install java and tomcat packages
  yum: pkg={{ item }} state=installed
  sudo: true
  with_items:
   - icedtea-web
   - tomcat6
   - tomcat6-webapps
   - tomcat6-admin-webapps
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- name: install java and tomcat packages
  apt: pkg={{ item }} state=installed
  sudo: true
  with_items:
   - openjdk-7-jre
   - tomcat6
   - tomcat6-extras
   - tomcat6-admin
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: setup the tomcat users file
  copy: src=tomcat/tomcat-users.xml dest=/etc/tomcat6/tomcat-users.xml
  sudo: true
  notify:
   - restart tomcat6

- name: change port of tomcat server
  copy: src=tomcat/server.xml dest=/etc/tomcat6/server.xml
  sudo: true

- name: ensure correct run level of tomcat
  service: name=tomcat6 enabled=yes
  sudo: true
  notify:
   - restart tomcat6

- name: force (re)start of tomcat6
  service: name=tomcat6 state=restarted
  sudo: true

- name: copy the tomcat6 users file
  copy: src=tomcat/tomcat-users.xml dest=/etc/tomcat6/tomcat-users.xml owner=tomcat6 group=tomcat6 mode=0644
  sudo: true
  notify:
   - restart tomcat6

- name: get iptables rules
  shell: iptables -L
  register: iptablesrules
  always_run: yes
  sudo: true

- name: add apache iptable rule
  command: /sbin/iptables -I INPUT 1 -p tcp --dport 8081 -j ACCEPT -m comment --comment "tomcat"
  sudo: true
  when: iptablesrules.stdout.find("tomcat") == -1
  notify:
   - save iptables

- name: download apache commons logging
  command: wget http://mirrors.ukfast.co.uk/sites/ftp.apache.org/commons/logging/binaries/commons-logging-1.2-bin.tar.gz creates=/home/{{ user }}/commons-logging-1.2-bin.tar.gz

- name: extract apache commons logging
  command: tar -zxf commons-logging-1.2-bin.tar.gz creates=/home/{{ user }}/commons-logging-1.2
  sudo: true

- name: list commons-logging files (in order to copy)
  command: ls -1 /home/{{ user }}/commons-logging-1.2/
  register: commonsfiles

- name: copy apache commons logging
  command: cp -r /home/{{ user }}/commons-logging-1.2/{{ item }} /usr/share/tomcat6/lib creates=/usr/share/tomcat6/lib/{{ item }}
  sudo: true
  with_items: commonsfiles.stdout_lines

- name: download SLF4J
  command: wget http://www.slf4j.org/dist/slf4j-1.7.7.tar.gz creates=/home/{{ user }}/slf4j-1.7.7.tar.gz

- name: extract SLF4J
  command: tar -zxf slf4j-1.7.7.tar.gz creates=/home/{{ user }}/slf4j-1.7.7

- name: list slf4j files (in order to copy)
  command: ls -1 /home/{{ user }}/slf4j-1.7.7/
  register: slf4jfiles

- name: copy SLF4J
  command: cp -r /home/{{ user }}/slf4j-1.7.7/{{ item }} /usr/share/tomcat6/lib creates=/usr/share/tomcat6/lib/{{ item }}
  sudo: true
  with_items: slf4jfiles.stdout_lines
  when: "'android' not in item and 'slf4j-log4j12' not in item and 'log4j-over-slf4j' not in item"

- name: download Solr
  command: wget http://www.mirrorservice.org/sites/ftp.apache.org/lucene/solr/4.7.2/solr-4.7.2.tgz creates=/home/{{ user }}/solr-4.7.2.tgz

- name: extract Solr
  command: tar -zxf /home/{{ user }}/solr-4.7.2.tgz creates=/home/{{ user }}/solr-4.7.2

- name: copy Solr war file
  command: cp /home/{{ user }}/solr-4.7.2/dist/solr-4.7.2.war /var/lib/tomcat6/webapps/solr.war creates=/var/lib/tomcat6/webapps/solr.war
  sudo: true

- name: list solr files (in order to copy)
  command: ls -1 /home/{{ user }}/solr-4.7.2/example/solr/
  register: solrfiles

- name: copy Solr instance
  command: cp -ar /home/{{ user }}/solr-4.7.2/example/solr/{{ item }} /home/solr creates=/home/solr/{{ item }}
  sudo: true
  with_items: solrfiles.stdout_lines
    
- name: rename the collection1 directory to vlad
  command: mv /home/solr/collection1 /home/solr/vlad creates=/home/solr/vlad
  sudo: true

- name: remove the collection1 collection if it is still there
  file: path=/home/solr/collection1 state=absent
  sudo: true

- name: change the name of the collection
  lineinfile: dest=/home/solr/vlad/core.properties regexp="^name=" insertafter="^name=" line="name=vlad"
  sudo: true

- name: create a solr lib directory
  file: path=/home/solr/lib state=directory
  sudo: true

- name: list all jar files that are part of solr (in order to copy)
  shell: ls -1 /home/{{ user }}/solr-4.7.2/dist/ | grep .jar
  register: solrjarfiles

- name: copy solr lib files
  command: cp /home/{{ user }}/solr-4.7.2/dist/{{ item }} /home/solr/lib/{{ item }} creates=/home/solr/lib/{{ item }}
  with_items: solrjarfiles.stdout_lines
  sudo: true

- name: force restart of tomcat6
  service: name=tomcat6 state=restarted
  sudo: true

- name: add WEB-INF directory
  command: mkdir -p /var/lib/tomcat6/webapps/solr/WEB-INF/
  sudo: true

- name: copy the web.xml tomcat solr integration file
  copy: src=tomcat/web.xml dest=/var/lib/tomcat6/webapps/solr/WEB-INF/web.xml
  sudo: true

- name: copy the properties file
  copy: src=tomcat/log4j.properties dest=/usr/share/tomcat6/lib/log4j.properties
  sudo: true

- name: make the vlad data directory
  command: mkdir /home/solr/vlad/data creates=/home/solr/vlad/data
  sudo: true

- name: get Drupal solr integration via search_api_solr
  git: repo=http://git.drupal.org/project/{{ drupal_solr_package }}.git version=7.x-1.6 dest=/home/{{ user }}/drupal_solr
  when: drupal_solr_package == "search_api_solr"

- name: get Drupal solr integration via apachesolr
  git: repo=http://git.drupal.org/project/{{ drupal_solr_package }}.git version=7.x-1.7 dest=/home/{{ user }}/drupal_solr
  when: drupal_solr_package == "apachesolr"

- name: copy Drupal Solr config into Solr
  shell: cp -r /home/{{ user }}/drupal_solr/solr-conf/4.x/. /home/solr/vlad/conf/
  when: drupal_solr_package == "search_api_solr"
  sudo: true
  notify:
   - restart tomcat6

- name: copy Drupal Solr config into Solr
  shell: cp -r /home/{{ user }}/drupal_solr/solr-conf/solr-4.x/. /home/solr/vlad/conf/
  when: drupal_solr_package == "apachesolr"
  sudo: true
  notify:
   - restart tomcat6

#- name: get patch for solrconfig.xml file
#  command: wget https://drupal.org/files/2107417-2.patch creates=/home/{{ user }}/2107417-2.patch
#  sudo: true
#  when: drupal_solr_package == "search_api_solr"
#  notify:
#   - restart tomcat6

#- name: patch solrconfig.xml file
#  command: patch /home/solr/vlad/conf/solrconfig.xml /home/{{ user }}/2107417-2.patch
#  sudo: true
#  when: drupal_solr_package == "search_api_solr"
#  notify:
#   - restart tomcat6

- name: make the lib/contrib directory for the extension to live in
  command: mkdir -p /home/solr/lib/contrib/ creates=/home/solr/lib/contrib/8
  sudo: true

- name: copy the needed class directories over
  command: cp -r /home/{{ user }}/solr-4.7.2/contrib/{{ item }} /home/solr/lib/contrib/{{ item }} creates=/home/solr/lib/contrib/{{ item }}
  sudo: true
  with_items:
    - analysis-extras
    - clustering
    - dataimporthandler
    - extraction
    - langid
    - uima
    - velocity

- name: ensure tomcat/Solr directory has correct owner
  file: path=/home/solr owner=tomcat6 group=tomcat6 recurse=yes
  sudo: true

- name: fix contrib extraction error in solrconfig.xml file
  lineinfile: dest=/home/solr/vlad/conf/solrconfig.xml regexp="<lib dir=\"../../contrib/extraction/lib\" />" insertafter="<lib dir=\"../../contrib/extraction/lib\" />" line="<lib dir=\"/home/solr/lib/contrib/extraction/lib\" />"
  sudo: true
  notify:
    - restart tomcat6

- name: fix contrib clustering error in solrconfig.xml file
  lineinfile: dest=/home/solr/vlad/conf/solrconfig.xml regexp="<lib dir=\"../../contrib/clustering/lib/\" />" insertafter="<lib dir=\"../../contrib/clustering/lib/\" />" line="<lib dir=\"/home/solr/lib/contrib/clustering/lib\" />"
  sudo: true
  notify:
    - restart tomcat6