---

- name: Ensure certain vlad_aux subdirectories exist
  file:
    path: /var/www/site/vlad_aux/{{ item }}
    state: directory
    mode: 0777
  sudo: true
  with_items:
    - drush_backups
    - db_io/drush_dumps

# Drush 6
# ---------------------------------------------------------

- name: drush | install drush via composer and run it once
  shell: /usr/local/bin/composer global require --no-progress --no-interaction drush/drush:6.* -d /usr/share/composer; /usr/share/composer/vendor/bin/drush
  args:
    creates: /usr/share/composer/vendor/bin/drush
  sudo: true

- name: drush | make drush available globally
  file:
    src: /usr/share/composer/vendor/bin/drush
    dest: /usr/bin/drush
    state: link
    force: yes
  sudo: true

- name: composer | prepare user .drush directory
  file:
    path: /home/{{ user }}/.drush
    state: directory
    owner: "{{ user }}"
    group: "{{ user }}"
    recurse: yes

- name: composer | ensure previous drush directory is absent
  file:
    path: /home/{{ user }}/.composer/vendor/drush/
    state: absent

- name: drush | download the site audit module
  command: drush dl site_audit --destination=/home/{{ user }}/.drush/site_audit --yes
    creates=/home/{{ user }}/.drush/site_audit
  notify: drush cc drush

- name: drush | download the Coder module
  command: drush dl coder-7.x-2.x --destination=/home/{{ user }}/.drush/coder --yes
    creates=/home/{{ user }}/.drush/coder
  notify: drush cc drush

- name: drush | download the Registry Rebuild module
  command: drush dl registry_rebuild --destination=/home/{{ user }}/.drush/registry_rebuild --yes
    creates=/home/{{ user }}/.drush/registry_rebuild
  notify: drush cc drush

- name: drush | Create drushrc.php file
  template:
    src: drushrc.php.j2
    dest: /home/{{ user }}/.drush/drushrc.php
  notify: drush cc drush


# Drush 7
# ---------------------------------------------------------

- name: drush | get latest version of Drush
  git:
    repo: https://github.com/drush-ops/drush.git
    dest: /home/{{ user }}/drush-master
    depth: 1
    version: master
- name: drush | set drush to executable
  file: path=/home/{{ user }}/drush-master mode=775

- name: drush | add drush-master alias to .bash_aliases file
  lineinfile:
    dest: /home/{{ user }}/.bash_aliases
    line: 'alias drush-master=/home/{{ user }}/drush-master/drush'
    create: yes

- name: drush | add drush7 alias to .bash_aliases file (matches Acquia Cloud & Pantheon standards)
  lineinfile:
    dest: /home/{{ user }}/.bash_aliases
    line: 'alias drush7=/home/{{ user }}/drush-master/drush'
    create: yes

- name: drush | run composer install in drush
  command: /usr/local/bin/composer install --no-progress --no-interaction
    chdir=/home/{{ user }}/drush-master
    creates=/home/{{ user }}/drush-master/vendor
