---

- include: drush.yml
  tags: drush

- include: drush_aliases.yml
  tags: drush_aliases

- include: drush_make.yml
  when: drush_make_file != ""
  tags: drush_make

- include: drupal_install.yml
  tags: drupal_install
