---

drush_composer_path: /usr/local/bin/composer
drush_install_path: /usr/local/share/drush
drush_keep_updated: no
drush_path: /usr/local/bin/drush
# See Drush repo for options:
# - https://github.com/drush-ops/drush/releases
# - https://github.com/drush-ops/drush/branches
# Examples:
# - 6.x
# - 7.x
# - 8.0.0-beta14
# - master
drush_version: master
