---
- name: apt-get | apt-get update
  apt: update_cache=yes cache_valid_time=3600
  sudo: true

- name: apt-get | ensure core packages are installed
  apt: pkg={{ item }} state=installed
  sudo: true
  with_items:
    - ssh-import-id
    - unzip
    - curl
    - atop
    - vim