---
- name: install prerequisites for Debian
  apt: pkg={{ item }} state=installed
  with_items:
   - graphviz
   - gcc
   - make
   - python-mysqldb
  become: true

- name: check that PECL xhprof is installed
  shell: pecl list | grep xhprof | wc -l
  register: pecl_xhprof_installed

- name: set pecl preferred state to beta
  command: pecl config-set preferred_state beta creates=/usr/lib/php5/20090626/xhprof.so
  when: php_version == '5.3'
  become: true

- name: install xhprof
  command: pecl install xhprof creates=/usr/lib/php5/20090626/xhprof.so
  when: php_version == '5.3' and pecl_xhprof_installed.stdout == '0'
  become: true

- name: set pecl preferred state to stable
  command: pecl config-set preferred_state stable creates=/usr/lib/php5/20090626/xhprof.so
  when: php_version == '5.3'
  become: true

- name: set pecl preferred state to beta
  command: pecl config-set preferred_state beta creates=/usr/lib/php5/20100525/xhprof.so
  when: php_version != '5.3'
  become: true

- name: install xhprof
  command: pecl install xhprof creates=/usr/lib/php5/20100525/xhprof.so
  when: php_version != '5.3' and pecl_xhprof_installed.stdout == '0'
  become: true
  notify:
    - restart apache2

- name: set pecl preferred state to stable
  command: pecl config-set preferred_state stable creates=/usr/lib/php5/20100525/xhprof.so
  when: php_version != '5.3'
  become: true

- name: setup xhprof ini files
  template: src=xhprof_ini.j2 dest=/etc/php5/apache2/conf.d/xhprof.ini
  become: true
  notify:
    - restart apache2

- name: get xhprof_html package
  git:
    repo: https://github.com/preinheimer/xhprof
    dest: /var/www/xhprof_html
    update: no
    depth: 1
    version: master
  become: true

- name: create xhprof_html application database
  mysql_db: name=xhprof state=present login_password={{ mysql_root_password }} login_user=root collation=utf8_general_ci

- name: create xhprof_html application database user
  mysql_user: name={{ dbuser }} password={{ dbpass }} priv="xhprof.*:ALL" host="{{ item }}" state=present login_password={{ mysql_root_password }} login_user=root append_privs=yes
  with_items:
   - '{{ local_ipv4_address.ansible_facts.ansible_default_ipv4.address }}'
   - 127.0.0.1
   - localhost

- name: ensure directory /var/www/xhprof_html/xhprof_lib exists
  file: path=/var/www/xhprof_html/xhprof_lib state=directory
  become: true

- name: copy SQL install script
  copy: src=install.mysql dest=/var/www/xhprof_html/install.sql
  become: true

- name: copy configuration file
  template: src=xhprof_config_php.j2 dest=/var/www/xhprof_html/xhprof_lib/config.php
  become: true

- name: run SQL install script
  shell: mysql --user={{ dbuser }} --password={{ dbpass }} xhprof < /var/www/xhprof_html/install.sql
  become: true

- name: check virtual host for xhprof include
  command: cat /etc/apache2/sites-enabled/{{ webserver_hostname }}.conf
  register: xhprof_include_present
  changed_when: false
  always_run: yes
  become: true

- name: add virtual server item if include not found
  lineinfile: dest=/etc/apache2/sites-enabled/{{ webserver_hostname }}.conf regexp="{{ item }}" insertbefore="^\<\/VirtualHost\>" line="{{ item }}"
  with_items:
    - '  php_value auto_prepend_file /var/www/xhprof_html/external/header.php'
    - '</VirtualHost>'
  when: xhprof_include_present.stdout.find('auto_prepend') == -1
  become: true
  notify:
    - restart apache2

- name: add vhost for xhprof.{{ webserver_hostname }}
  template: src=apache_xhprof_vhost.j2 dest=/etc/apache2/sites-available/xhprof.{{ webserver_hostname }}.conf
  become: true
  when: ansible_os_family == "Debian"
  notify:
    - restart apache2

- name: enable the xhprof site
  command: a2ensite xhprof.{{ webserver_hostname }}.conf creates=/etc/apache2/sites-enabled/xhprof.{{ webserver_hostname }}.conf
  become: true
  when: ansible_os_family == "Debian"
  notify:
    - restart apache2

- name: ensure xhprof directory permissions
  file: path=/var/www/xhprof_html mode=0777 recurse=yes
  become: true
