---
- hosts: all
  gather_facts: false
  vars_files:
    - "./vars/defaults/vagrant.yml"
    - "./vars/defaults/general.yml"
    - "./vars/defaults/install.yml"
    - "./roles/mysql/defaults/main.yml"
    - [ "../../settings/vlad_settings.yml", "../../../settings/vlad_settings.yml", "../settings.yml", "vars/dummy_settings.yml" ]
    - [ "../../settings/vlad_local_settings.yml", "../../../settings/vlad_local_settings.yml", "../local_settings.yml", "vars/dummy_settings.yml" ]

  tasks:
  - name: local actions destroy | install python-mysqldb package
    apt: pkg=python-mysqldb state=installed
    tags: mysql
    when: mysql_install
    ignore_errors: yes
    sudo: true

  - name: local actions destroy | dump vlad database
    mysql_db: name={{ dbname[0] }} state=dump target=/var/www/site/vlad_aux/db_io/vlad_destroy.sql.gz login_password={{ mysql_root_password }} login_user=root
    when: mysql_install
    ignore_errors: yes
    sudo: true
