---

# This is based on geerlingguy's Drush role [2015/07/27] but with tweaks:
#
# - Doesn't clone the entire Drush repo (depth)
# - Role dependencies have been removed
# - Added 'drush_composer_path' var to fill in for missing dependencies
# - Installs Console_Table for Drush 6 & below

# ------------------------------------------------------------------------------

- name: Clone Drush from GitHub
  git:
    repo: https://github.com/drush-ops/drush.git
    dest: "{{ drush_install_path }}"
    version: "{{ drush_version }}"
    update: "{{ drush_keep_updated }}"
    depth: 1

- name: Install Drush dependencies with Composer
  shell: >
    {{ drush_composer_path }} install --prefer-source --no-interaction
    chdir={{ drush_install_path }}
    creates={{ drush_install_path }}/vendor/autoload.php

- name: Create drush symlink
  file:
    src: "{{ drush_install_path }}/drush"
    dest: "{{ drush_path }}"
    state: link

# Intended for Drush 6 & below only.
# Could be triggered if drush_version is set to an obscure branch name but wont
# hurt besides potentially adding a little to provisioning time.
- name: Install Console_Table
  command: >
    pear install Console_Table
    creates=/usr/share/php/Console/Table.php
  when: "{{ drush_version | truncate(1, true, '') | int | version_compare('7', '<') }} and drush_version != 'master'"

- name: Run drush command to finish setup
  command: "{{ drush_path }}"
  register: drush_result
  changed_when: "'Execute a drush command' not in drush_result.stdout"
