---
- hosts: all
  user: vagrant
  gather_facts: false
  vars_files:
    - "./vars/defaults/vagrant.yml"
    - "./vars/defaults/general.yml"
    - "./vars/defaults/install.yml"
    - "./roles/mysql/defaults/main.yml"
    - "../merged_user_settings.yml"

  tasks:
  - name: local actions destroy | install python-mysqldb package
    apt: pkg=python-mysqldb state=installed
    tags: mysql
    when: mysql_install
    ignore_errors: yes
    become: true

  - name: local actions destroy | ensure vlad_aux/db_io/halt_destroy/ exists
    file:
      path: /var/www/site/vlad_aux/db_io/halt_destroy
      state: directory
      mode: 0777
    when: vlad_db_dump_on_halt_destroy
    become: true

  - name: local actions destroy | dump all databases
    mysql_db:
      name: "{{ item }}"
      state: dump
      target: /var/www/site/vlad_aux/db_io/halt_destroy/{{ item }}.sql.gz
      login_user: root
      login_password: "{{ mysql_root_password }}"
    with_items: dbname
    when: mysql_install and vlad_db_dump_on_halt_destroy
    ignore_errors: yes
    become: true
