---
- hosts: all
  user: vagrant
  gather_facts: false
  vars_files:
    - "./vars/defaults/vagrant.yml"
    - "./vars/defaults/general.yml"
    - "../merged_user_settings.yml"

  tasks:

  - name: local actions | check local ip address is defined
    fail: msg="The system may not be provisioned according to the CMDB status."
    when: local_ip_address is not defined

  - name: local actions | set local inventory directory
    set_fact: vlad_host_inventory_dir='{{ vlad_local_inventory_dir }}'
    delegate_to: 127.0.0.1

  - name: local actions | create local host.ini file
    template: src=templates/host.j2 dest="{{ vlad_host_inventory_dir }}/host.ini"
    delegate_to: 127.0.0.1

  # SSH identities

  - name: local actions | establish current username on host machine
    command: whoami
    register: host_user
    when: use_host_id != false and is_windows != true
    delegate_to: 127.0.0.1
    changed_when: false

  - name: local actions | check that ~/.ssh/config exists on host machine
    stat: path=/Users/{{ host_user.stdout }}/.ssh/config
    register: ssh_config_file
    when: use_host_id != false and is_windows != true
    delegate_to: 127.0.0.1
    failed_when: ssh_config_file.stat.exists == false
    changed_when: false

  - name: local actions | check for "ForwardAgent yes" in ~/.ssh/config
    local_action: command grep "ForwardAgent yes" ~/.ssh/config
    when: use_host_id != false and is_windows != true
    changed_when: false

  - name: local actions | add default identities from host to guest
    local_action: command ssh-add
    when: use_host_id and is_windows != true

  - name: local actions | add custom identity from host to guest
    local_action: command ssh-add {{ use_host_id }}
    when: use_host_id != true and use_host_id != false and is_windows != true
