---

# Keep these all in Git repo format for now please.

- src: https://github.com/hashbangcode/ansible-role-aberdeencloud-cli
  version: 1.0.0.beta.1
  name: aberdeencloud_cli

- src: https://github.com/hashbangcode/ansible-role-pantheon-cli
  version: 1.0.0.beta.4
  name: pantheon_cli

- src: https://github.com/hashbangcode/ansible-role-imagemagick
  version: 1.0.0.beta.1
  name: imagemagick

- src: https://github.com/hashbangcode/ansible-role-sendmail
  version: 1.0.0.beta.1
  name: sendmail

- src: https://github.com/hashbangcode/ansible-role-tomcat
  version: 1.0.0.beta.1
  name: tomcat

- src: https://github.com/hashbangcode/ansible-role-solr
  version: 1.0.0.beta.2
  name: solr

- src: https://github.com/hashbangcode/ansible-role-drush
  version: 1.0.0.beta.2
  name: drush
