---
# PHP Version, can be one of:
# - "5.3"
# - "5.4"
# - "5.5"
# - "5.6"
# Note that Ubuntu14 won't install < PHP5.4 so you'll get PHP5.5+
# Vlad will error when a version that isn't understood is used
php_version: "5.5"

# php.ini settings
php_memory_limit: 512M
php_max_execution_time: 60
php_max_input_time: 60
php_max_input_vars: 2000
php_post_max_size: 100M
php_upload_max_filesize: 100M
php_display_errors: On
php_display_startup_errors: On
php_html_errors: On
php_date_timezone: Europe/London

# Install PECL uploadprogress
php_pecl_uploadprogress: false

# PHP APC Settings
apc_rfc1867: '1'
apc_shm_size: '256M'
apc_shm_segments: '1'
apc_num_files_hint: '0'
