---

- name: ensure certain vlad_aux subdirectories exist
  file: path=/var/www/site/vlad_aux/{{ item }} state=directory mode=0777
  sudo: true
  with_items:
    - tmp
    - db_io

- name: set permissions on /tmp directory
  file: path=/tmp mode=0777 recurse=yes
  sudo: yes

- include: aptget.yml
  when: ansible_os_family == "Debian"

- include: yum.yml
  when: ansible_os_family == "RedHat"

- include: git.yml

- include: python.yml
  when: is_windows == false

- include: ssh_config.yml

- include: shell.yml
