---
- name: composer | install Composer (shared)
  shell: curl -sS https://getcomposer.org/installer | php && mv composer.phar /usr/local/bin/composer creates=/usr/local/bin/composer
  tags: composer
  sudo: true

- name: composer | prepare Composer shared directory
  file:
    path=/usr/share/composer
    state=directory
  tags: composer
  sudo: true

- name: composer | ensure previous composer vendor directory is not in the user's PATH
  lineinfile:
    dest=/home/{{ user }}/.bashrc
    state=absent
    line='export PATH=$PATH:/home/{{ user }}/.composer/vendor/bin/'
  tags: composer

- name: composer | add Composer shared vendor directory to path
  template:
    src=composer.j2
    dest=/etc/profile.s/composer.sh
    mode="a+x"
  tags: composer
