---
- name: get ius rpm
  command: wget http://dl.iuscommunity.org/pub/ius/stable/CentOS/6/x86_64/ius-release-1.0-13.ius.centos6.noarch.rpm chdir=/home/{{ user }} creates=/home/{{ user }}/ius-release-1.0-13.ius.centos6.noarch.rpm
  tags: php

- name: install ius
  command: rpm -Uvh /home/{{ user }}/ius-release-1.0-13.ius.centos6.noarch.rpm chdir=/home/{{ user }} creates=/etc/yum.repos.d/ius.repo
  tags: php
  sudo: true

- name: install php packages
  yum: pkg={{ item }} state=latest
  with_items:
   - php
   - php-devel
   - php-apc
   - php-pear
   - php-cli
   - php-common
   - php-dom
   - php-gd
   - php-mysql
   - php-xmlrpc
   - php-soap
   - php-curl
   - php-pdo
   - php-mbstring
  tags: php
  sudo: true
  when: php_version != '5.4'
  notify:
    - restart httpd

- name: install php packages
  yum: pkg={{ item }} state=latest
  with_items:
   - php54
   - php54-devel
   - php54-pecl-apc
   - php54-pear
   - php54-cli
   - php54-common
   - php54-dom
   - php54-gd
   - php54-mysql
   - php54-xmlrpc
   - php54-soap
   - php54-curl
   - php54-pdo
   - php54-mbstring
  tags: php
  sudo: true
  when: php_version == '5.4'
  notify:
    - restart httpd

- name: change php apache2 memory_limit
  lineinfile: dest=/etc/php.ini regexp="^[#|;]?memory_limit =" insertafter="^[#|;]?memory_limit =" line="memory_limit = {{ php_memory_limit }}"
  tags: php
  sudo: true
  notify:
    - restart httpd

- name: change php apache2 max_execution_time
  lineinfile: dest=/etc/php.ini regexp="^[#|;]?max_execution_time =" insertafter="^[#|;]?max_execution_time =" line="max_execution_time = {{ php_max_execution_time }}"
  tags: php
  sudo: true
  notify:
    - restart httpd

- name: change php apache2 post_max_size
  lineinfile: dest=/etc/php.ini regexp="^[#|;]?post_max_size =" insertafter="^[#|;]?post_max_size =" line="post_max_size = {{ php_post_max_size }}"
  tags: php
  sudo: true
  notify:
    - restart httpd

- name: change php apache2 upload_max_filesize
  lineinfile: dest=/etc/php.ini regexp="^[#|;]?upload_max_filesize =" insertafter="^[#|;]?upload_max_filesize = " line="upload_max_filesize = {{ php_upload_max_filesize }}"
  tags: php
  sudo: true
  notify:
    - restart httpd

- name: change php apache2 max_execution_time
  lineinfile: dest=/etc/php.ini regexp="[#|;]?max_execution_time =" insertafter="^[#|;]?max_execution_time =" line="max_execution_time = {{ php_max_execution_time }}"
  tags: php
  sudo: true
  notify:
    - restart httpd

- name: change php apache2 display_errors
  lineinfile: dest=/etc/php.ini regexp="^[#|;]?display_errors =" insertafter="^[#|;]?display_errors =" line="display_errors = {{ php_display_errors }}"
  tags: php
  sudo: true
  notify:
    - restart httpd

- name: change php apache2 display_startup_errors
  lineinfile: dest=/etc/php.ini regexp="^[#|;]?display_startup_errors =" insertafter="^[#|;]?display_startup_errors =" line="display_startup_errors = {{ php_display_startup_errors }}"
  tags: php
  sudo: true
  notify:
    - restart httpd

- name: change php apache2 html_errors
  lineinfile: dest=/etc/php.ini regexp="^[#|;]?html_errors =" insertafter="^[#|;]?html_errors =" line="html_errors = {{ php_html_errors }}"
  tags: php
  sudo: true
  notify:
    - restart httpd

- name: change php apache2 date.timezone
  lineinfile: dest=/etc/php.ini regexp="^[#|;]?date.timezone =" insertafter="^[#|;]?date.timezone =" line="date.timezone = {{ php_date_timezone }}"
  tags: php
  sudo: true
  notify:
    - restart httpd

- name: change APC configuration file apc.ini
  template: src=redhat_php_apache2_apc.ini.j2 dest=/etc/php.d/apc.ini
  tags: php
  sudo: true
  notify:
    - restart httpd

- name: don't expose php
  lineinfile: dest=/etc/php.ini regexp="^(;*)expose_php =" insertafter="^(;*)expose_php =" line="expose_php = Off"
  sudo: true
  notify:
    - restart httpd

- name: check, what PECL uploadprogress is installed
  command: pecl list | grep uploadprogress | wc -l
  register: pecl_uploadprogress_installed
  changed_when: false

- name: install PECL uploadprogress
  command: pecl install uploadprogress creates=/usr/lib64/php/modules/uploadprogress.so
  tags: php
  sudo: true
  when: php_pecl_uploadprogress and pecl_uploadprogress_installed.stdout == '0'

- name: add PECL uploadprogress apache php.ini setting
  lineinfile: dest=/etc/php.ini state=present line="extension=uploadprogress.so"
  tags: php
  sudo: true
  when: php_pecl_uploadprogress
  notify:
    - restart httpd