---
- name: xdebug | install Xdebug PHP component
  yum: pkg=php-pecl-xdebug state=installed
  register: xdebug_installed
  tags: xdebug
  when: php_version == '5.3'
  sudo: true

- name: xdebug | install Xdebug PHP component
  yum: pkg=php54-pecl-xdebug state=installed
  register: xdebug_installed
  tags: xdebug
  when: php_version == '5.4'
  sudo: true

- name: xdebug | get first two lines of /etc/php.d/xdebug.ini
  command: head -n 2 /etc/php.d/xdebug.ini
  when: xdebug_installed.changed
  register: xdebug_first_line
  tags: xdebug
  sudo: true

- name: xdebug | update xdebug configuration file
  template: src=php_apache2_xdebug.ini.j2 dest=/etc/php.d/xdebug.ini
  when: xdebug_installed.changed
  tags: xdebug
  sudo: true